on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B package -DskipTests=false -Darguments="-Dmaven.javadoc.skip=true"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: SimpleWorldEdit
          path: target/SimpleWorldEdit-1.0.0.jar